baseURL = 'https://g14ayushi.github.io'
languageCode = 'en-us'
title = 'Ayushi Codes'
theme = "paper"
author = 'Ayushi Gupta'
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]


[params]
color = 'linen'

github = 'g14ayushi'
linkedin = 'ayushigupta9370'
instagram = 'ayushi_gupta478'

avatar = 'ayushi.gupta.9370@gmail.com'
name = 'Ayushi Gupta'
bio = """Software Engineer, ZHCET AMU"""
favicon = "favicon/logo.png"
# monoDarkIcon = true

[params.giscus]
repo = 'g14ayushi/g14ayushi.github.io'        # see https://giscus.app for more details
repoId = 'R_kgDOM63Zvw='
category = 'General'
categoryId = 'DIC_kwDOM63Zv84CuxiT'
mapping = 'pathname'
theme = 'light'
lang = 'en'


# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

#[[menu.main]]
#identifier = "posts"
#name = "Posts"
#url = "/posts/"
#weight = 20

[[menu.main]]
identifier = "Project"
name = "Projects"
url = "/projects/"
weight = 30


[taxonomies]
category = "categories"
tag = "tags"
series = "series"


[privacy]
[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true


[services]
[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
